use crate::core::config::Settings;
use crate::services::{get_service_pid, is_systemd_service_running, ServiceStatus};
use std::path::PathBuf;
use tokio::process::Command;

pub struct HttpService {
    settings: Settings,
}

impl HttpService {
    pub fn new(settings: Settings) -> Self {
        Self { settings }
    }

    pub async fn generate_config(&self) -> anyhow::Result<()> {
        let tftp_root = &self.settings.tftp.root_dir;

        // Generate Apache2 configuration for serving boot files
        let apache_config = format!(
            r#"# Generated by diskless-boot-server
# Apache2 configuration for PXE boot file serving

<VirtualHost *:8080>
    ServerName {hostname}
    DocumentRoot {tftp_root}
    
    <Directory {tftp_root}>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
        
        # Enable directory listing for easier debugging
        Options +Indexes
        IndexOptions FancyIndexing
    </Directory>
    
    # Serve iPXE scripts
    <Location /boot.ipxe>
        Header set Content-Type "text/plain"
    </Location>
    
    # Logging
    ErrorLog ${{APACHE_LOG_DIR}}/pxe-error.log
    CustomLog ${{APACHE_LOG_DIR}}/pxe-access.log combined
</VirtualHost>

# Listen on port 8080
Listen 8080
"#,
            hostname = self.settings.server.hostname,
            tftp_root = tftp_root.display(),
        );

        // Write Apache2 site configuration
        let config_path = PathBuf::from("/etc/apache2/sites-available/diskless-pxe.conf");
        std::fs::write(&config_path, apache_config)?;

        tracing::info!("Apache2 configuration written to {}", config_path.display());

        // Enable the site
        Command::new("a2ensite")
            .arg("diskless-pxe")
            .status()
            .await?;

        // Enable required modules
        Command::new("a2enmod").arg("headers").status().await?;

        tracing::info!("Apache2 site enabled");
        Ok(())
    }

    pub async fn start(&self) -> anyhow::Result<()> {
        // Generate config first
        self.generate_config().await?;

        // Start Apache2
        Command::new("pkexec")
            .args(["systemctl", "start", "apache2"])
            .status()
            .await?;

        tracing::info!("Apache2 service started");
        Ok(())
    }

    pub async fn stop(&self) -> anyhow::Result<()> {
        Command::new("pkexec")
            .args(["systemctl", "stop", "apache2"])
            .status()
            .await?;

        tracing::info!("Apache2 service stopped");
        Ok(())
    }

    pub async fn reload(&self) -> anyhow::Result<()> {
        // Regenerate config
        self.generate_config().await?;

        // Reload Apache2
        Command::new("pkexec")
            .args(["systemctl", "reload", "apache2"])
            .status()
            .await?;

        tracing::info!("Apache2 service reloaded");
        Ok(())
    }

    pub async fn status(&self) -> anyhow::Result<ServiceStatus> {
        let running = is_systemd_service_running("apache2").await?;
        let pid = if running {
            get_service_pid("apache2").await?
        } else {
            None
        };

        Ok(ServiceStatus {
            running,
            pid,
            message: if running {
                "Apache2 HTTP server is running on port 8080".to_string()
            } else {
                "Apache2 HTTP server is not running".to_string()
            },
        })
    }
}
