use crate::core::config::Settings;
use crate::services::{get_service_pid, is_systemd_service_running, ServiceStatus};
use tokio::process::Command;

pub struct NfsService {
    settings: Settings,
}

impl NfsService {
    pub fn new(settings: Settings) -> Self {
        Self { settings }
    }

    pub async fn generate_config(&self) -> anyhow::Result<()> {
        let exports_content = format!(
            "# Generated by diskless-boot-server\n\
            {} *(ro,sync,no_subtree_check,no_root_squash)\n",
            self.settings.nfs.exports_dir.display()
        );

        std::fs::write("/etc/exports", exports_content)?;

        tracing::info!("NFS exports written to /etc/exports");
        Ok(())
    }

    pub async fn add_export(&self, path: &str, options: &str) -> anyhow::Result<()> {
        let mut content = std::fs::read_to_string("/etc/exports")?;
        content.push_str(&format!("{} {}\n", path, options));
        std::fs::write("/etc/exports", content)?;

        // Re-export
        Command::new("exportfs").args(["-ra"]).status().await?;

        tracing::info!("NFS export added: {}", path);
        Ok(())
    }

    pub async fn start(&self) -> anyhow::Result<()> {
        Command::new("systemctl")
            .args(["start", "nfs-kernel-server"])
            .status()
            .await?;
        tracing::info!("NFS service started");
        Ok(())
    }

    pub async fn stop(&self) -> anyhow::Result<()> {
        Command::new("systemctl")
            .args(["stop", "nfs-kernel-server"])
            .status()
            .await?;
        tracing::info!("NFS service stopped");
        Ok(())
    }

    pub async fn reload(&self) -> anyhow::Result<()> {
        Command::new("exportfs").args(["-ra"]).status().await?;
        tracing::info!("NFS exports reloaded");
        Ok(())
    }

    pub async fn status(&self) -> anyhow::Result<ServiceStatus> {
        let running = is_systemd_service_running("nfs-kernel-server").await?;
        let pid = get_service_pid("nfs-kernel-server").await?;
        Ok(ServiceStatus {
            running,
            pid,
            message: if running {
                "NFS server is running".to_string()
            } else {
                "NFS server is not running".to_string()
            },
        })
    }
}
