use crate::infrastructure::nvmeof::NVMET_TCP_PORT;

#[must_use]
pub fn nvme_tcp_uri(server_ip: &str, nqn: &str) -> String {
    format!(
        "nvme://{}:{}/{}",
        server_ip.trim(),
        NVMET_TCP_PORT,
        nqn.trim()
    )
}

#[must_use]
pub fn render_windows_nvmeof_boot(nqn: &str) -> String {
    format!(
        r##"# Experimental Windows Server NVMe/TCP boot path.
# Stock iPXE first chains snponly-nvmeof.efi. Its embedded startup script sets
# diskless-nvmeof=1 and re-enters the normal per-client menu.
set nvme-nqn {nqn}
isset ${{diskless-nvmeof}} || goto load_nvmeof_firmware
set nvme-root nvme://${{next-server}}:{port}/${{nvme-nqn}}
set keep-san 1
set net0/gateway 0.0.0.0
echo NVMe/TCP target: ${{nvme-root}}
sanboot ${{nvme-root}} || goto failed

:load_nvmeof_firmware
chain http://${{next-server}}/snponly-nvmeof.efi || goto failed
"##,
        port = NVMET_TCP_PORT,
    )
}

/// Render the common iPXE entry point used by every client.
///
/// The common script does not contain client boot policy. It normalizes the
/// active NIC MAC address to the same 12-hex-character form used by
/// `client_mac_script_path()` and then chains the generated per-client menu.
#[must_use]
pub fn render_client_dispatcher_autoexec(http_port: u16) -> String {
    let port_suffix = if http_port == 80 {
        String::new()
    } else {
        format!(":{http_port}")
    };

    format!(
        r##"#!ipxe
# Generated by diskless-manager.
# Common dispatcher: client policy lives in clients/<mac>.ipxe.

dhcp || goto failed
set boot-url http://${{next-server}}{port_suffix}
set client-mac ${{net0/mac:hexraw}}

echo Diskless Manager client MAC: ${{net0/mac}}
echo Loading ${{boot-url}}/clients/${{client-mac}}.ipxe
chain ${{boot-url}}/clients/${{client-mac}}.ipxe || goto unknown_client

:unknown_client
echo No generated client iPXE menu exists for ${{net0/mac}}.
echo Expected: clients/${{client-mac}}.ipxe
shell

:failed
echo DHCP failed; cannot locate the diskless-manager boot server.
shell
"##,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builds_nvme_tcp_uri() {
        assert_eq!(
            nvme_tcp_uri("192.168.1.250", "nqn.2026-09.local.diskless:client.pc001"),
            "nvme://192.168.1.250:4420/nqn.2026-09.local.diskless:client.pc001"
        );
    }

    #[test]
    fn script_chains_custom_firmware_before_nvme_sanboot() {
        let script = render_windows_nvmeof_boot("nqn.2026-09.local.diskless:client.pc001");
        assert!(script.contains("isset ${diskless-nvmeof} || goto load_nvmeof_firmware"));
        assert!(script.contains("chain http://${next-server}/snponly-nvmeof.efi"));
        assert!(script.contains("nvme://${next-server}:4420/${nvme-nqn}"));
        assert!(script.contains("set keep-san 1"));
        assert!(script.contains("sanboot ${nvme-root}"));
    }

    #[test]
    fn dispatcher_chains_mac_specific_script() {
        let script = render_client_dispatcher_autoexec(80);
        assert!(script.contains("set client-mac ${net0/mac:hexraw}"));
        assert!(script.contains("chain ${boot-url}/clients/${client-mac}.ipxe"));
        assert!(script.contains("set boot-url http://${next-server}"));
    }

    #[test]
    fn dispatcher_supports_non_default_http_port() {
        let script = render_client_dispatcher_autoexec(4433);
        assert!(script.contains("set boot-url http://${next-server}:4433"));
    }
}
