use crate::core::client::ClientManager;
use crate::core::config::Settings;
use crate::services::{get_service_pid, is_systemd_service_running, ServiceStatus};
use sqlx::SqlitePool;
use std::path::PathBuf;
use tokio::process::Command;

pub struct DhcpService {
    settings: Settings,
    db_pool: SqlitePool,
}

impl DhcpService {
    pub fn new(settings: Settings, db_pool: SqlitePool) -> Self {
        Self { settings, db_pool }
    }

    pub async fn generate_config(&self) -> anyhow::Result<()> {
        let config = &self.settings.dhcp;
        let server = &self.settings.server;

        let mut dhcp_config = format!(
            r#"# Generated by diskless-boot-server
# Do not edit manually

authoritative;
default-lease-time {lease_time};
max-lease-time {max_lease};

option domain-name "{domain}";
option domain-name-servers {dns};

subnet {subnet} netmask {netmask} {{
    range {range_start} {range_end};
    option routers {gateway};
    option subnet-mask {netmask};
    
    # PXE Boot options
    next-server {server_ip};
    
    # BIOS boot
    class "pxeclient-bios" {{
        match if substring (option vendor-class-identifier, 0, 9) = "PXEClient" and not substring (option vendor-class-identifier, 0, 20) = "PXEClient:Arch:00007";
        filename "pxelinux.0";
    }}
    
    # UEFI x64 boot
    class "pxeclient-uefi64" {{
        match if substring (option vendor-class-identifier, 0, 20) = "PXEClient:Arch:00007";
        filename "efi64/syslinux.efi";
    }}
    
    # UEFI x32 boot  
    class "pxeclient-uefi32" {{
        match if substring (option vendor-class-identifier, 0, 20) = "PXEClient:Arch:00006";
        filename "efi32/syslinux.efi";
    }}
    
    # iPXE boot
    if exists user-class and option user-class = "iPXE" {{
        filename "http://{server_ip}:8080/boot.ipxe";
    }}
}}

"#,
            lease_time = config.lease_time,
            max_lease = config.lease_time * 2,
            domain = server.domain,
            dns = config.dns_servers.join(", "),
            subnet = calculate_network(&config.range_start, &config.subnet_mask)?,
            netmask = config.subnet_mask,
            range_start = config.range_start,
            range_end = config.range_end,
            gateway = config.gateway,
            server_ip = server.ip_address,
        );

        // Add static host entries for registered clients
        let client_manager = ClientManager::new(self.db_pool.clone());
        let clients = client_manager.list().await?;

        for client in clients {
            if let Some(ip) = &client.ip_address {
                dhcp_config.push_str(&format!(
                    r#"
host {name} {{
    hardware ethernet {mac};
    fixed-address {ip};
    option host-name "{name}";
}}
"#,
                    name = client.name,
                    mac = client.mac_address,
                    ip = ip,
                ));
            }
        }

        // Write configuration to default DHCP config path
        let config_path = PathBuf::from("/etc/dhcp/dhcpd.conf");
        if let Some(parent) = config_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&config_path, dhcp_config)?;

        tracing::info!("DHCP configuration written to {}", config_path.display());
        Ok(())
    }

    pub async fn start(&self) -> anyhow::Result<()> {
        Command::new("systemctl")
            .args(["start", "isc-dhcp-server"])
            .status()
            .await?;
        tracing::info!("DHCP service started");
        Ok(())
    }

    pub async fn stop(&self) -> anyhow::Result<()> {
        Command::new("systemctl")
            .args(["stop", "isc-dhcp-server"])
            .status()
            .await?;
        tracing::info!("DHCP service stopped");
        Ok(())
    }

    pub async fn reload(&self) -> anyhow::Result<()> {
        Command::new("systemctl")
            .args(["reload", "isc-dhcp-server"])
            .status()
            .await?;
        tracing::info!("DHCP service reloaded");
        Ok(())
    }

    pub async fn status(&self) -> anyhow::Result<ServiceStatus> {
        let running = is_systemd_service_running("isc-dhcp-server").await?;
        let pid = get_service_pid("isc-dhcp-server").await?;
        Ok(ServiceStatus {
            running,
            pid,
            message: if running {
                "DHCP server is running".to_string()
            } else {
                "DHCP server is not running".to_string()
            },
        })
    }
}

fn calculate_network(ip: &str, netmask: &str) -> anyhow::Result<String> {
    let ip_parts: Vec<u8> = ip
        .split('.')
        .map(|s| s.parse())
        .collect::<Result<Vec<_>, _>>()?;
    let mask_parts: Vec<u8> = netmask
        .split('.')
        .map(|s| s.parse())
        .collect::<Result<Vec<_>, _>>()?;

    let network: Vec<String> = ip_parts
        .iter()
        .zip(mask_parts.iter())
        .map(|(ip, mask)| (ip & mask).to_string())
        .collect();

    Ok(network.join("."))
}
