use std::net::Ipv4Addr;
use std::sync::Arc;

use crate::core::client::ClientManager;
use crate::core::config::{DhcpConfig, Settings};
use crate::services::{
    get_service_pid, is_systemd_service_running, run_sudo_command, write_with_sudo_tee,
    ServiceStatus,
};
use log::info;
use sqlx::SqlitePool;
use std::path::PathBuf;

pub struct DhcpService {
    pub(crate) settings: Arc<Settings>,
    pub(crate) db_pool: SqlitePool,
}

impl DhcpService {
    pub fn new(settings: Settings, db_pool: SqlitePool) -> Self {
        Self {
            settings: Arc::new(settings),
            db_pool,
        }
    }

    pub async fn generate_config(&self) -> anyhow::Result<()> {
        let config = &self.settings.dhcp;
        validate_dhcp_config(config)?;
        validate_server_consistency(&self.settings)?;

        let interfaces = self.settings.server.interface.join(" ");
        if interfaces.trim().is_empty() {
            anyhow::bail!("At least one DHCP interface must be configured");
        }
        for interface in &self.settings.server.interface {
            validate_interface_name(interface)?;
        }

        let dhcp_config = render_dhcp_config(config);
        let dhcp_path = PathBuf::from("/etc/dhcp/dhcpd.conf");
        if let Some(parent) = dhcp_path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| anyhow::anyhow!("Failed to create directory: {}", e))?;
        }

        crate::dhcp::replace_dhcp_config(&dhcp_config)
            .await
            .map_err(anyhow::Error::msg)?;

        let default_config = format!(
            "# Generated by diskless-manager\nINTERFACESv4=\"{}\"\nINTERFACESv6=\"\"\n",
            interfaces
        );
        write_with_sudo_tee("/etc/default/isc-dhcp-server", &default_config).await?;

        info!("DHCP configuration and /etc/default/isc-dhcp-server written");
        Ok(())
    }

    pub async fn start(&self) -> anyhow::Result<()> {
        run_sudo_command(["systemctl", "start", "isc-dhcp-server"]).await?;
        info!("DHCP service started");
        Ok(())
    }

    pub async fn stop(&self) -> anyhow::Result<()> {
        run_sudo_command(["systemctl", "stop", "isc-dhcp-server"]).await?;
        info!("DHCP service stopped");
        Ok(())
    }

    pub async fn reload(&self) -> anyhow::Result<()> {
        run_sudo_command(["systemctl", "restart", "isc-dhcp-server"]).await?;
        info!("DHCP service reloaded");
        Ok(())
    }

    /// Validate the complete ISC DHCP configuration, including clients.conf,
    /// before a caller reloads the service.
    pub async fn validate_config(&self) -> anyhow::Result<()> {
        validate_dhcp_config(&self.settings.dhcp)?;
        validate_server_consistency(&self.settings)?;
        for interface in &self.settings.server.interface {
            validate_interface_name(interface)?;
        }
        run_sudo_command(["dhcpd", "-t", "-cf", "/etc/dhcp/dhcpd.conf"]).await?;
        Ok(())
    }

    pub async fn get_config(&self) -> anyhow::Result<String> {
        let config_path = PathBuf::from("/etc/dhcp/dhcpd.conf");
        if config_path.exists() {
            let content = std::fs::read_to_string(&config_path)?;
            Ok(content)
        } else {
            validate_dhcp_config(&self.settings.dhcp)?;
            validate_server_consistency(&self.settings)?;
            Ok(render_dhcp_config(&self.settings.dhcp))
        }
    }

    pub async fn status(&self) -> anyhow::Result<ServiceStatus> {
        let running = is_systemd_service_running("isc-dhcp-server").await?;
        let pid = get_service_pid("isc-dhcp-server").await?;
        Ok(ServiceStatus {
            running,
            pid,
            message: if running {
                "DHCP server is running".to_string()
            } else {
                "DHCP server is not running".to_string()
            },
        })
    }

    pub async fn generate_client_configs(&self) -> anyhow::Result<()> {
        let client_manager = ClientManager::new(self.db_pool.clone());
        let clients = client_manager.list().await?;
        let server_ip = self.settings.dhcp.next_server_ip.trim();
        let server_ip = if server_ip.is_empty() {
            self.settings.server.ip_address.trim()
        } else {
            server_ip
        };
        let client_config = clients
            .into_iter()
            .filter(|client| client.enabled && !client.ip.is_empty() && client.ip != "N/A")
            .filter_map(|client| {
                client
                    .target_iqn
                    .as_deref()
                    .filter(|iqn| !iqn.trim().is_empty())
                    .map(|iqn| {
                        crate::dhcp::create_dhcp_entry_for_server(
                            &client.name,
                            &client.mac,
                            &client.ip,
                            iqn,
                            server_ip,
                        )
                    })
            })
            .collect::<Vec<_>>()
            .join("\n\n");

        crate::dhcp::replace_dhcp_clients_config(&format!("{client_config}\n"))
            .await
            .map_err(anyhow::Error::msg)?;

        info!("Static DHCP client configuration validated and written");
        Ok(())
    }
}

/// Render the complete manager-owned ISC DHCP configuration from one canonical
/// template. Keeping this separate from `get_config` prevents the fallback
/// configuration from drifting away from the configuration written by
/// `generate_config`.
fn render_dhcp_config(config: &DhcpConfig) -> String {
    format!(
        r#"# Generated by diskless-manager
# Global Config
option space ipxe;
option ipxe-encap-opts code 175 = encapsulate ipxe;
option ipxe.priority code 1 = signed integer 8;
option ipxe.keep-san code 8 = unsigned integer 8;
option ipxe.skip-san-boot code 9 = unsigned integer 8;
option ipxe.syslogs code 85 = string;
option ipxe.cert code 91 = string;
option ipxe.privkey code 92 = string;
option ipxe.crosscert code 93 = string;
option ipxe.no-pxedhcp code 176 = unsigned integer 8;
option ipxe.bus-id code 177 = string;
option ipxe.san-filename code 188 = string;
option ipxe.bios-drive code 189 = unsigned integer 8;
option ipxe.username code 190 = string;
option ipxe.password code 191 = string;
option ipxe.reverse-username code 192 = string;
option ipxe.reverse-password code 193 = string;
option ipxe.version code 235 = string;
option iscsi-initiator-iqn code 203 = string;

# iPXE feature indicators
option ipxe.pxeext code 16 = unsigned integer 8;
option ipxe.iscsi code 17 = unsigned integer 8;
option ipxe.aoe code 18 = unsigned integer 8;
option ipxe.http code 19 = unsigned integer 8;
option ipxe.https code 20 = unsigned integer 8;
option ipxe.tftp code 21 = unsigned integer 8;
option ipxe.ftp code 22 = unsigned integer 8;
option ipxe.dns code 23 = unsigned integer 8;
option ipxe.bzimage code 24 = unsigned integer 8;
option ipxe.multiboot code 25 = unsigned integer 8;
option ipxe.slam code 26 = unsigned integer 8;
option ipxe.srp code 27 = unsigned integer 8;
option ipxe.nbi code 32 = unsigned integer 8;
option ipxe.pxe code 33 = unsigned integer 8;
option ipxe.elf code 34 = unsigned integer 8;
option ipxe.comboot code 35 = unsigned integer 8;
option ipxe.efi code 36 = unsigned integer 8;
option ipxe.fcoe code 37 = unsigned integer 8;
option ipxe.vlan code 38 = unsigned integer 8;
option ipxe.menu code 39 = unsigned integer 8;
option ipxe.sdi code 40 = unsigned integer 8;
option ipxe.nfs code 41 = unsigned integer 8;
option client-architecture code 93 = unsigned integer 16;
option ipxe.no-pxedhcp 1;

# DHCP Server Configuration
default-lease-time 86400;
max-lease-time 86400;
authoritative;
allow booting;
allow bootp;
one-lease-per-client true;

class "pxeclients" {{
  match if substring(option vendor-class-identifier, 0, 9) = "PXEClient";
}}

subnet {} netmask {} {{
    pool {{
        allow members of "pxeclients";
        range {} {};
    }}
    option routers {};
    option domain-name-servers {}, {};
    option broadcast-address {};

    # PXE Boot Configuration
    next-server {};
    if exists user-class and option user-class = "iPXE" {{
        filename "http://{}/{}";
    }} elsif option client-architecture = 00:00 {{
        filename "{}";
    }} elsif option client-architecture = 00:06 {{
        filename "{}";
    }} elsif option client-architecture = 00:07 {{
        filename "{}";
    }}
}}

# Static leases are managed separately.
include "/etc/dhcp/clients.conf";
"#,
        config.subnet_ip,
        config.subnet_mask,
        config.start_ip,
        config.end_ip,
        config.gateway_ip,
        config.dns_server1,
        config.dns_server2,
        config.broadcast_ip,
        config.next_server_ip,
        config.boot_server_ip,
        config.boot_script,
        config.boot_file_legacy,
        config.boot_file_uefi32,
        config.boot_file_uefi64,
    )
}

fn validate_dhcp_config(config: &DhcpConfig) -> anyhow::Result<()> {
    let subnet = parse_ipv4("subnet_ip", &config.subnet_ip)?;
    let mask = parse_ipv4("subnet_mask", &config.subnet_mask)?;
    let mask_u32 = u32::from(mask);

    if mask_u32 == 0 || (mask_u32 & (mask_u32 + 1)) != 0 {
        anyhow::bail!("subnet_mask must be a contiguous non-zero IPv4 netmask");
    }

    let network = u32::from(subnet) & mask_u32;
    if network != u32::from(subnet) {
        anyhow::bail!("subnet_ip {} is not the network address for {}", subnet, mask);
    }

    let broadcast = network | !mask_u32;
    let configured_broadcast = parse_ipv4("broadcast_ip", &config.broadcast_ip)?;
    if u32::from(configured_broadcast) != broadcast {
        anyhow::bail!(
            "broadcast_ip {} does not match subnet {}/{}",
            configured_broadcast,
            subnet,
            mask
        );
    }

    let start = parse_ipv4("start_ip", &config.start_ip)?;
    let end = parse_ipv4("end_ip", &config.end_ip)?;
    if u32::from(start) > u32::from(end) {
        anyhow::bail!("start_ip must not be greater than end_ip");
    }
    if u32::from(start) <= network || u32::from(end) >= broadcast {
        anyhow::bail!("DHCP pool must be inside the subnet and exclude network/broadcast addresses");
    }
    if !in_subnet(u32::from(start), network, mask_u32)
        || !in_subnet(u32::from(end), network, mask_u32)
    {
        anyhow::bail!("DHCP pool must be inside the configured subnet");
    }

    let gateway = parse_ipv4("gateway_ip", &config.gateway_ip)?;
    if !in_subnet(u32::from(gateway), network, mask_u32) {
        anyhow::bail!("gateway_ip {} is outside the configured subnet", gateway);
    }

    parse_ipv4("next_server_ip", &config.next_server_ip)?;
    parse_ipv4("boot_server_ip", &config.boot_server_ip)?;
    parse_ipv4("dns_server1", &config.dns_server1)?;
    parse_ipv4("dns_server2", &config.dns_server2)?;

    for value in [
        &config.boot_script,
        &config.boot_file_legacy,
        &config.boot_file_uefi32,
        &config.boot_file_uefi64,
    ] {
        validate_boot_filename(value)?;
    }

    Ok(())
}

fn validate_server_consistency(settings: &Settings) -> anyhow::Result<()> {
    let server_ip = parse_ipv4("server.ip_address", &settings.server.ip_address)?;
    let server_mask = parse_ipv4("server.netmask", &settings.server.netmask)?;
    let server_gateway = parse_ipv4("server.gateway", &settings.server.gateway)?;
    let dhcp = &settings.dhcp;

    if settings.server.interface.is_empty() {
        anyhow::bail!("server.interface must contain at least one interface");
    }

    if server_ip != parse_ipv4("dhcp.boot_server_ip", &dhcp.boot_server_ip)? {
        anyhow::bail!(
            "server.ip_address ({server_ip}) must match dhcp.boot_server_ip ({})",
            dhcp.boot_server_ip
        );
    }
    if server_ip != parse_ipv4("dhcp.next_server_ip", &dhcp.next_server_ip)? {
        anyhow::bail!(
            "server.ip_address ({server_ip}) must match dhcp.next_server_ip ({})",
            dhcp.next_server_ip
        );
    }
    if server_mask != parse_ipv4("dhcp.subnet_mask", &dhcp.subnet_mask)? {
        anyhow::bail!(
            "server.netmask ({server_mask}) must match dhcp.subnet_mask ({})",
            dhcp.subnet_mask
        );
    }
    if server_gateway != parse_ipv4("dhcp.gateway_ip", &dhcp.gateway_ip)? {
        anyhow::bail!(
            "server.gateway ({server_gateway}) must match dhcp.gateway_ip ({})",
            dhcp.gateway_ip
        );
    }

    Ok(())
}

fn parse_ipv4(field: &str, value: &str) -> anyhow::Result<Ipv4Addr> {
    value
        .trim()
        .parse::<Ipv4Addr>()
        .map_err(|error| anyhow::anyhow!("{} must be a valid IPv4 address: {}", field, error))
}

fn in_subnet(value: u32, network: u32, mask: u32) -> bool {
    value & mask == network
}

fn validate_interface_name(value: &str) -> anyhow::Result<()> {
    let value = value.trim();
    if value.is_empty()
        || value.len() > 15
        || !value
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || matches!(character, '_' | '-' | '.' | ':'))
    {
        anyhow::bail!("invalid network interface name: {value:?}");
    }
    Ok(())
}

fn validate_boot_filename(value: &str) -> anyhow::Result<()> {
    let value = value.trim();
    if value.is_empty()
        || value == "."
        || value == ".."
        || value.starts_with('/')
        || value.contains("..")
        || value.contains('/')
        || value.contains('\\')
        || value.contains('"')
        || value.contains(';')
        || value.chars().any(char::is_whitespace)
    {
        anyhow::bail!("boot filename must be a safe relative filename: {value:?}");
    }
    Ok(())
}

#[expect(
    dead_code,
    reason = "Utility function kept for potential future DHCP network calculations"
)]
fn calculate_network(ip: &str, netmask: &str) -> anyhow::Result<String> {
    let ip_parts: Vec<u8> = ip
        .split('.')
        .map(|s| s.parse())
        .collect::<Result<Vec<_>, _>>()?;
    let mask_parts: Vec<u8> = netmask
        .split('.')
        .map(|s| s.parse())
        .collect::<Result<Vec<_>, _>>()?;

    let network: Vec<String> = ip_parts
        .iter()
        .zip(mask_parts.iter())
        .map(|(ip, mask)| (ip & mask).to_string())
        .collect();

    Ok(network.join("."))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_dhcp_config_matches_production_network() {
        let config = DhcpConfig::default();
        assert_eq!(config.subnet_ip, "192.168.1.0");
        assert_eq!(config.subnet_mask, "255.255.255.0");
        assert_eq!(config.start_ip, "192.168.1.100");
        assert_eq!(config.end_ip, "192.168.1.200");
        assert_eq!(config.gateway_ip, "192.168.1.254");
        assert_eq!(config.dns_server1, "192.168.1.254");
        assert_eq!(config.dns_server2, "9.9.9.9");
        assert_eq!(config.next_server_ip, "192.168.1.250");
        assert_eq!(config.boot_server_ip, "192.168.1.250");
    }

    #[test]
    fn default_server_config_matches_production_network() {
        let server = crate::core::config::ServerConfig::default();
        assert_eq!(server.interface, vec!["eno2"]);
        assert_eq!(server.ip_address, "192.168.1.250");
        assert_eq!(server.netmask, "255.255.255.0");
        assert_eq!(server.gateway, "192.168.1.254");
    }

    #[test]
    fn production_dhcp_config_passes_semantic_validation() {
        validate_dhcp_config(&DhcpConfig::default()).expect("default configuration must be valid");
    }

    #[test]
    fn production_server_and_dhcp_settings_are_consistent() {
        let settings = Settings::default();
        validate_server_consistency(&settings).expect("default settings must be consistent");
    }

    #[test]
    fn invalid_broadcast_is_rejected() {
        let mut config = DhcpConfig::default();
        config.broadcast_ip = "192.168.1.254".to_string();
        assert!(validate_dhcp_config(&config).is_err());
    }

    #[test]
    fn invalid_pool_order_is_rejected() {
        let mut config = DhcpConfig::default();
        config.start_ip = "192.168.1.200".to_string();
        config.end_ip = "192.168.1.100".to_string();
        assert!(validate_dhcp_config(&config).is_err());
    }

    #[test]
    fn non_contiguous_mask_is_rejected() {
        let mut config = DhcpConfig::default();
        config.subnet_mask = "255.0.255.0".to_string();
        assert!(validate_dhcp_config(&config).is_err());
    }

    #[test]
    fn unsafe_boot_filename_is_rejected() {
        let mut config = DhcpConfig::default();
        config.boot_script = "../../autoexec.ipxe".to_string();
        assert!(validate_dhcp_config(&config).is_err());
    }

    #[test]
    fn unsafe_interface_name_is_rejected() {
        assert!(validate_interface_name("eno2; rm -rf /").is_err());
        assert!(validate_interface_name("eno2").is_ok());
    }

    #[test]
    fn canonical_renderer_contains_expected_pxe_flow() {
        let rendered = render_dhcp_config(&DhcpConfig::default());
        assert!(rendered.contains("option ipxe.san-filename code 188 = string;"));
        assert!(rendered.contains("next-server 192.168.1.250;"));
        assert!(rendered.contains("filename \"http://192.168.1.250/autoexec.ipxe\";"));
        assert!(rendered.contains("filename \"undionly.kpxe\";"));
        assert!(rendered.contains("filename \"ipxe.efi\";"));
        assert!(rendered.contains("filename \"snponly.efi\";"));
        assert_eq!(rendered.matches("option ipxe.http code 19").count(), 1);
        assert!(rendered.contains("include \"/etc/dhcp/clients.conf\";"));
    }
}
