use std::path::PathBuf;
use std::sync::Arc;

use crate::core::config::Settings;
use crate::infrastructure::{
    dhcp::{publish_client_ipxe, BootReservation},
    pxe::render_client_dispatcher_autoexec,
};
use crate::services::{
    get_service_pid, is_systemd_service_running, run_sudo_command, write_with_sudo_tee,
    ServiceStatus,
};
use log::info;

pub struct HttpService {
    pub(crate) settings: Arc<Settings>,
}

impl HttpService {
    pub async fn generate_config(&self) -> anyhow::Result<()> {
        let distro = crate::platform::detect();
        let root_dir = PathBuf::from(&self.settings.http.root_dir);
        let apache_config = format!(
            r#"# Generated by diskless-boot-server
# Apache configuration for PXE boot file serving

<VirtualHost {server_ip}:{port}>
    ServerName {hostname}
    DocumentRoot {root_dir}

    <Directory {root_dir}>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
        Options +Indexes
        IndexOptions FancyIndexing
    </Directory>

    ErrorLog {log_dir}/pxe-error.log
    CustomLog {log_dir}/pxe-access.log combined
</VirtualHost>
"#,
            server_ip = self.settings.http.server_ip,
            port = self.settings.http.port,
            hostname = self.settings.server.hostname,
            root_dir = root_dir.display(),
            log_dir = distro.http_log_dir(),
        );

        let config_path = PathBuf::from(distro.http_config_path());
        if let Some(parent) = config_path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| anyhow::anyhow!("Failed to create parent directory: {e}"))?;
        }

        let config_str = config_path
            .to_str()
            .ok_or_else(|| anyhow::anyhow!("HTTP config path is not valid UTF-8"))?;
        write_with_sudo_tee(config_str, &apache_config).await?;

        self.publish_autoexec().await?;
        self.publish_cached_client_menus().await?;
        info!("Apache configuration written to {}", config_path.display());

        // Fedora's httpd automatically loads every *.conf file dropped into
        // /etc/httpd/conf.d/ and ships with mod_headers enabled, so the
        // a2ensite/a2enmod dance is only required on Debian.
        if distro.is_debian() {
            run_sudo_command(["a2ensite", "diskless-server"]).await?;
            run_sudo_command(["a2enmod", "headers"]).await?;
            info!("Apache2 site enabled");
        }
        Ok(())
    }

    async fn publish_autoexec(&self) -> anyhow::Result<()> {
        let autoexec = render_client_dispatcher_autoexec(
            self.settings.http.port,
            crate::infrastructure::pxe::ENROLL_PORT,
        );
        let root_dir = PathBuf::from(&self.settings.http.root_dir);
        let path = root_dir.join("autoexec.ipxe");
        let path = path
            .to_str()
            .ok_or_else(|| anyhow::anyhow!("HTTP root directory is not valid UTF-8"))?;

        write_with_sudo_tee(path, &autoexec).await?;
        info!("Published client-dispatching iPXE autoexec to {}", path);
        Ok(())
    }

    /// Rebuild MAC-specific boot menus for clients loaded from the database
    /// into the runtime configuration cache during AppState startup.
    ///
    /// This repairs existing installations automatically when the HTTP service
    /// is generated, started, or reloaded. New clients are also generated
    /// transactionally by `IscDhcpPublisher` during provisioning.
    async fn publish_cached_client_menus(&self) -> anyhow::Result<()> {
        let config = crate::config::get_config();
        let server_ip = if self.settings.dhcp.next_server_ip.trim().is_empty() {
            self.settings.server.ip_address.trim()
        } else {
            self.settings.dhcp.next_server_ip.trim()
        };

        let mut published = 0usize;
        for client in config.clients {
            if !client.enabled {
                continue;
            }

            let Some(target_iqn) = client
                .target_iqn
                .as_deref()
                .map(str::trim)
                .filter(|value| !value.is_empty())
            else {
                tracing::warn!(
                    client = %client.name,
                    "skipping per-client iPXE menu because no target IQN is persisted"
                );
                continue;
            };

            let reservation = BootReservation {
                client_name: client.name.clone(),
                mac: client.mac.clone(),
                ip: client.ip.clone(),
                target_iqn: target_iqn.to_string(),
                server_ip: server_ip.to_string(),
                // Repair-menu path preserves the legacy open attach; CHAP
                // menus are (re)published by the enrollment/update flows.
                chap: None,
            };

            publish_client_ipxe(&reservation).await.map_err(|error| {
                anyhow::anyhow!(
                    "failed to regenerate iPXE menu for client '{}': {}",
                    client.name,
                    error
                )
            })?;
            published += 1;
        }

        info!("Regenerated {} per-client iPXE menu file(s)", published);
        Ok(())
    }

    pub async fn start(&self) -> anyhow::Result<()> {
        self.generate_config().await?;
        let service = crate::platform::detect().http_service();
        run_sudo_command(["systemctl", "start", service]).await?;
        info!("{} service started", service);
        Ok(())
    }

    pub async fn stop(&self) -> anyhow::Result<()> {
        let service = crate::platform::detect().http_service();
        run_sudo_command(["systemctl", "stop", service]).await?;
        info!("{} service stopped", service);
        Ok(())
    }

    pub async fn reload(&self) -> anyhow::Result<()> {
        self.generate_config().await?;
        let service = crate::platform::detect().http_service();
        if crate::services::is_systemd_service_running(service).await? {
            run_sudo_command(["systemctl", "reload", service]).await?;
        } else {
            // A stopped service cannot be reloaded; start it instead.
            info!(
                "{} service not active; restarting instead of reloading",
                service
            );
            run_sudo_command(["systemctl", "restart", service]).await?;
        }
        info!("{} service reloaded", service);
        Ok(())
    }

    pub async fn get_config(&self) -> anyhow::Result<String> {
        let config_path = PathBuf::from(crate::platform::detect().http_config_path());
        if config_path.exists() {
            return Ok(std::fs::read_to_string(config_path)?);
        }

        let root_dir = PathBuf::from(&self.settings.http.root_dir);
        Ok(format!(
            r#"# Generated by diskless-boot-server
<VirtualHost {server_ip}:{port}>
    ServerName {hostname}
    DocumentRoot {root_dir}
    <Directory {root_dir}>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>
</VirtualHost>
"#,
            server_ip = self.settings.http.server_ip,
            port = self.settings.http.port,
            hostname = self.settings.server.hostname,
            root_dir = root_dir.display(),
        ))
    }

    pub async fn status(&self) -> anyhow::Result<ServiceStatus> {
        let service = crate::platform::detect().http_service();
        let running = is_systemd_service_running(service).await?;
        let pid = if running {
            get_service_pid(service).await?
        } else {
            None
        };

        Ok(ServiceStatus { running, pid })
    }
}
