use crate::core::config::Settings;
use crate::services::{get_service_pid, is_systemd_service_running, ServiceStatus};
use std::path::PathBuf;
use tokio::process::Command;

pub struct HttpService {
    settings: Settings,
}

impl HttpService {
    pub fn new(settings: Settings) -> Self {
        Self { settings }
    }

    pub async fn generate_config(&self) -> anyhow::Result<()> {
        let tftp_root = &self.settings.tftp.root_dir;

        // Generate Apache2 configuration for serving boot files
        let apache_config = format!(
            r#"# Generated by diskless-boot-server
# Apache2 configuration for PXE boot file serving

<VirtualHost *:8080>
    ServerName {hostname}
    DocumentRoot {tftp_root}
    
    <Directory {tftp_root}>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
        
        # Enable directory listing for easier debugging
        Options +Indexes
        IndexOptions FancyIndexing
    </Directory>
    
    # Serve iPXE scripts
    <Location /boot.ipxe>
        Header set Content-Type "text/plain"
    </Location>
    
    # Logging
    ErrorLog ${{APACHE_LOG_DIR}}/pxe-error.log
    CustomLog ${{APACHE_LOG_DIR}}/pxe-access.log combined
</VirtualHost>

# Listen on port 8080
Listen 8080
"#,
            hostname = self.settings.server.hostname,
            tftp_root = tftp_root.display(),
        );

        // Write Apache2 site configuration
        let config_path = PathBuf::from("/etc/apache2/sites-available/diskless-server.conf");

        // Ensure parent directory exists
        if let Some(parent) = config_path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| anyhow::anyhow!("Failed to create parent directory: {}", e))?;
        }

        // Use pkexec to write to system configuration file
        use tokio::process::Command;
        let mut child = Command::new("pkexec")
            .arg("tee")
            .arg(config_path.to_string_lossy().as_ref())
            .stdin(std::process::Stdio::piped())
            .stdout(std::process::Stdio::null())
            .spawn()
            .map_err(|e| anyhow::anyhow!("Failed to spawn pkexec tee: {}", e))?;

        if let Some(ref mut stdin) = child.stdin {
            use tokio::io::AsyncWriteExt;
            stdin
                .write_all(apache_config.as_bytes())
                .await
                .map_err(|e| anyhow::anyhow!("Failed to write config to stdin: {}", e))?;
            stdin
                .flush()
                .await
                .map_err(|e| anyhow::anyhow!("Failed to flush stdin: {}", e))?;
        }

        let status = child
            .wait()
            .await
            .map_err(|e| anyhow::anyhow!("Failed to wait for pkexec tee: {}", e))?;

        if !status.success() {
            return Err(anyhow::anyhow!(
                "Failed to write Apache config file with pkexec tee"
            ));
        }

        tracing::info!("Apache2 configuration written to {}", config_path.display());

        // Enable the site
        Command::new("a2ensite")
            .arg("diskless-server")
            .status()
            .await?;

        // Enable required modules
        Command::new("a2enmod").arg("headers").status().await?;

        tracing::info!("Apache2 site enabled");
        Ok(())
    }

    pub async fn start(&self) -> anyhow::Result<()> {
        // Generate config first
        self.generate_config().await?;

        // Start Apache2
        Command::new("pkexec")
            .args(["systemctl", "start", "apache2"])
            .status()
            .await?;

        tracing::info!("Apache2 service started");
        Ok(())
    }

    pub async fn stop(&self) -> anyhow::Result<()> {
        Command::new("pkexec")
            .args(["systemctl", "stop", "apache2"])
            .status()
            .await?;

        tracing::info!("Apache2 service stopped");
        Ok(())
    }

    pub async fn reload(&self) -> anyhow::Result<()> {
        // Regenerate config
        self.generate_config().await?;

        // Reload Apache2
        Command::new("pkexec")
            .args(["systemctl", "reload", "apache2"])
            .status()
            .await?;

        tracing::info!("Apache2 service reloaded");
        Ok(())
    }

    pub async fn get_config(&self) -> anyhow::Result<String> {
        let config_path = PathBuf::from("/etc/apache2/sites-available/diskless-server.conf");
        if config_path.exists() {
            let content = std::fs::read_to_string(&config_path)?;
            Ok(content)
        } else {
            // Return default configuration if file doesn't exist
            let tftp_root = &self.settings.tftp.root_dir;
            let apache_config = format!(
                r#"# Generated by diskless-boot-server
# Apache2 configuration for PXE boot file serving

<VirtualHost *:8080>
    ServerName {hostname}
    DocumentRoot {tftp_root}

    <Directory {tftp_root}>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted

        # Enable directory listing for easier debugging
        Options +Indexes
        IndexOptions FancyIndexing
    </Directory>

    # Serve iPXE scripts
    <Location /boot.ipxe>
        Header set Content-Type "text/plain"
    </Location>

    # Logging
    ErrorLog ${{APACHE_LOG_DIR}}/pxe-error.log
    CustomLog ${{APACHE_LOG_DIR}}/pxe-access.log combined
</VirtualHost>

# Listen on port 8080
Listen 8080
"#,
                hostname = self.settings.server.hostname,
                tftp_root = tftp_root.display(),
            );
            Ok(apache_config)
        }
    }

    pub async fn status(&self) -> anyhow::Result<ServiceStatus> {
        let running = is_systemd_service_running("apache2").await?;
        let pid = if running {
            get_service_pid("apache2").await?
        } else {
            None
        };

        Ok(ServiceStatus {
            running,
            pid,
            message: if running {
                "Apache2 HTTP server is running on port 8080".to_string()
            } else {
                "Apache2 HTTP server is not running".to_string()
            },
        })
    }
}
