use crate::core::config::Settings;
use crate::services::{get_service_pid, is_systemd_service_running, ServiceStatus};
use std::path::PathBuf;
use tokio::process::Command;

pub struct NfsService {
    settings: Settings,
}

impl NfsService {
    pub fn new(settings: Settings) -> Self {
        Self { settings }
    }

    pub async fn generate_config(&self) -> anyhow::Result<()> {
        let exports_content = format!(
            "# Generated by diskless-boot-server\n\
            {} *(ro,sync,no_subtree_check,no_root_squash)\n",
            self.settings.nfs.exports_dir.display()
        );

        std::fs::write("/etc/exports", exports_content)?;

        tracing::info!("NFS exports written to /etc/exports");
        Ok(())
    }

    pub async fn add_export(&self, path: &str, options: &str) -> anyhow::Result<()> {
        // Read the existing exports file
        let content = std::fs::read_to_string("/etc/exports").unwrap_or_default();
        let new_content = format!("{}{} {}\n", content, path, options);

        // Use pkexec to write to system configuration file
        use tokio::process::Command;
        let mut child = Command::new("pkexec")
            .arg("tee")
            .arg("/etc/exports")
            .stdin(std::process::Stdio::piped())
            .stdout(std::process::Stdio::null())
            .spawn()
            .map_err(|e| anyhow::anyhow!("Failed to spawn pkexec tee: {}", e))?;

        if let Some(ref mut stdin) = child.stdin {
            use tokio::io::AsyncWriteExt;
            stdin
                .write_all(new_content.as_bytes())
                .await
                .map_err(|e| anyhow::anyhow!("Failed to write config to stdin: {}", e))?;
            stdin
                .flush()
                .await
                .map_err(|e| anyhow::anyhow!("Failed to flush stdin: {}", e))?;
        }

        let status = child
            .wait()
            .await
            .map_err(|e| anyhow::anyhow!("Failed to wait for pkexec tee: {}", e))?;

        if !status.success() {
            return Err(anyhow::anyhow!(
                "Failed to write NFS exports file with pkexec tee"
            ));
        }

        // Re-export
        Command::new("exportfs").args(["-ra"]).status().await?;

        tracing::info!("NFS export added: {}", path);
        Ok(())
    }

    pub async fn start(&self) -> anyhow::Result<()> {
        Command::new("systemctl")
            .args(["start", "nfs-kernel-server"])
            .status()
            .await?;
        tracing::info!("NFS service started");
        Ok(())
    }

    pub async fn stop(&self) -> anyhow::Result<()> {
        Command::new("systemctl")
            .args(["stop", "nfs-kernel-server"])
            .status()
            .await?;
        tracing::info!("NFS service stopped");
        Ok(())
    }

    pub async fn reload(&self) -> anyhow::Result<()> {
        Command::new("exportfs").args(["-ra"]).status().await?;
        tracing::info!("NFS exports reloaded");
        Ok(())
    }

    pub async fn get_config(&self) -> anyhow::Result<String> {
        let config_path = PathBuf::from("/etc/exports");
        if config_path.exists() {
            let content = std::fs::read_to_string(&config_path)?;
            Ok(content)
        } else {
            // Return default configuration if file doesn't exist
            let exports_content = format!(
                "# Generated by diskless-boot-server\n\
                {} *(ro,sync,no_subtree_check,no_root_squash)\n",
                self.settings.nfs.exports_dir.display()
            );
            Ok(exports_content)
        }
    }

    pub async fn status(&self) -> anyhow::Result<ServiceStatus> {
        let running = is_systemd_service_running("nfs-kernel-server").await?;
        let pid = get_service_pid("nfs-kernel-server").await?;
        Ok(ServiceStatus {
            running,
            pid,
            message: if running {
                "NFS server is running".to_string()
            } else {
                "NFS server is not running".to_string()
            },
        })
    }
}
