use crate::core::config::Settings;
use crate::services::{
    get_service_pid, is_systemd_service_running, write_with_sudo_tee, ServiceStatus,
};
use std::path::PathBuf;
use tokio::process::Command;

pub struct SambaService {
    settings: Settings,
}

impl SambaService {
    pub fn new(settings: Settings) -> Self {
        Self { settings }
    }

    pub async fn start(&self) -> anyhow::Result<()> {
        // Create share directory if it doesn't exist using elevated privileges
        let share_path = &self.settings.samba.share_path;
        let share_path_str = share_path.to_string_lossy();
        let mkdir_result = Command::new("pkexec")
            .args(["mkdir", "-p", &share_path_str])
            .status()
            .await;

        if let Err(e) = mkdir_result {
            tracing::error!(
                "Failed to execute pkexec for creating Samba share directory {}: {}",
                share_path.display(),
                e
            );
            return Err(anyhow::anyhow!(
                "Failed to execute pkexec for creating Samba share directory {}: {}",
                share_path.display(),
                e
            ));
        }

        let mkdir_status = mkdir_result.unwrap();
        if !mkdir_status.success() {
            tracing::error!(
                "Failed to create Samba share directory {}: pkexec mkdir returned non-zero exit code",
                share_path.display()
            );
            return Err(anyhow::anyhow!(
                "Failed to create Samba share directory {}: pkexec mkdir returned non-zero exit code",
                share_path.display()
            ));
        }

        // Generate and write Samba configuration
        self.generate_config().await?;

        // Start Samba services
        Command::new("pkexec")
            .args(["systemctl", "start", "smbd"])
            .status()
            .await?;

        Command::new("pkexec")
            .args(["systemctl", "start", "nmbd"])
            .status()
            .await?;

        tracing::info!("Samba service started");
        Ok(())
    }

    pub async fn stop(&self) -> anyhow::Result<()> {
        Command::new("pkexec")
            .args(["systemctl", "stop", "smbd"])
            .status()
            .await?;

        Command::new("pkexec")
            .args(["systemctl", "stop", "nmbd"])
            .status()
            .await?;

        tracing::info!("Samba service stopped");
        Ok(())
    }

    pub async fn reload(&self) -> anyhow::Result<()> {
        self.generate_config().await?;

        Command::new("pkexec")
            .arg("systemctl")
            .args(["restart", "smbd"])
            .status()
            .await?;

        tracing::info!("Samba service reloaded");
        Ok(())
    }

    pub async fn status(&self) -> anyhow::Result<ServiceStatus> {
        let smbd_running = is_systemd_service_running("smbd").await?;
        let nmbd_running = is_systemd_service_running("nmbd").await?;
        let running = smbd_running && nmbd_running;

        let pid = if running {
            get_service_pid("smbd").await?
        } else {
            None
        };

        Ok(ServiceStatus {
            running,
            pid,
            message: if running {
                "Samba server is running (smbd + nmbd)".to_string()
            } else if smbd_running {
                "Only smbd is running".to_string()
            } else if nmbd_running {
                "Only nmbd is running".to_string()
            } else {
                "Samba server is not running".to_string()
            },
        })
    }

    pub async fn get_config(&self) -> anyhow::Result<String> {
        let config_path = PathBuf::from("/etc/samba/smb.conf");
        if config_path.exists() {
            let content = std::fs::read_to_string(&config_path)?;
            Ok(content)
        } else {
            // Return default configuration if file doesn't exist
            let config = &self.settings.samba;

            let smb_conf = format!(
                r#"# Generated by diskless-boot-server
# Do not edit manually

[global]
   workgroup = {}
   server string = Diskless Boot Server
   netbios name = {}
   security = user
   map to guest = Bad User
   dns proxy = no

   # Logging
   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file

[{}]
   path = {}
   browseable = yes
   writable = {}
   guest ok = {}
   read only = {}
   create mask = 0755
   directory mask = 0755
   force user = nobody
   force group = nogroup
"#,
                config.workgroup,
                self.settings.server.hostname,
                config.share_name,
                config.share_path.display(),
                if config.read_only { "no" } else { "yes" },
                if config.guest_ok { "yes" } else { "no" },
                if config.read_only { "yes" } else { "no" },
            );
            Ok(smb_conf)
        }
    }

    pub async fn generate_config(&self) -> anyhow::Result<()> {
        let config = &self.settings.samba;

        let smb_conf = format!(
            r#"# Generated by diskless-boot-server
# Do not edit manually

[global]
   workgroup = {}
   server string = Diskless Boot Server
   netbios name = {}
   security = user
   map to guest = Bad User
   dns proxy = no
   
   # Logging
   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file

[{}]
   path = {}
   browseable = yes
   writable = {}
   guest ok = {}
   read only = {}
   create mask = 0755
   directory mask = 0755
   force user = nobody
   force group = nogroup
"#,
            config.workgroup,
            self.settings.server.hostname,
            config.share_name,
            config.share_path.display(),
            if config.read_only { "no" } else { "yes" },
            if config.guest_ok { "yes" } else { "no" },
            if config.read_only { "yes" } else { "no" },
        );

        write_with_sudo_tee("/etc/samba/smb.conf", &smb_conf).await?;

        tracing::info!("Samba configuration written to /etc/samba/smb.conf");
        Ok(())
    }
}
