use crate::core::config::Settings;
use crate::services::{get_service_pid, is_systemd_service_running, ServiceStatus};
use tokio::process::Command;

pub struct SambaService {
    settings: Settings,
}

impl SambaService {
    pub fn new(settings: Settings) -> Self {
        Self { settings }
    }

    pub async fn start(&self) -> anyhow::Result<()> {
        // Create share directory if it doesn't exist
        std::fs::create_dir_all(&self.settings.samba.share_path)?;

        // Generate and write Samba configuration
        self.generate_config().await?;

        // Start Samba services
        Command::new("systemctl")
            .args(["start", "smbd"])
            .status()
            .await?;

        Command::new("systemctl")
            .args(["start", "nmbd"])
            .status()
            .await?;

        tracing::info!("Samba service started");
        Ok(())
    }

    pub async fn stop(&self) -> anyhow::Result<()> {
        Command::new("systemctl")
            .args(["stop", "smbd"])
            .status()
            .await?;

        Command::new("systemctl")
            .args(["stop", "nmbd"])
            .status()
            .await?;

        tracing::info!("Samba service stopped");
        Ok(())
    }

    pub async fn reload(&self) -> anyhow::Result<()> {
        self.generate_config().await?;

        Command::new("systemctl")
            .args(["reload", "smbd"])
            .status()
            .await?;

        tracing::info!("Samba service reloaded");
        Ok(())
    }

    pub async fn status(&self) -> anyhow::Result<ServiceStatus> {
        let smbd_running = is_systemd_service_running("smbd").await?;
        let nmbd_running = is_systemd_service_running("nmbd").await?;
        let running = smbd_running && nmbd_running;

        let pid = if running {
            get_service_pid("smbd").await?
        } else {
            None
        };

        Ok(ServiceStatus {
            running,
            pid,
            message: if running {
                format!("Samba server is running (smbd + nmbd)")
            } else if smbd_running {
                "Only smbd is running".to_string()
            } else if nmbd_running {
                "Only nmbd is running".to_string()
            } else {
                "Samba server is not running".to_string()
            },
        })
    }

    async fn generate_config(&self) -> anyhow::Result<()> {
        let config = &self.settings.samba;

        let smb_conf = format!(
            r#"# Generated by diskless-boot-server
# Do not edit manually

[global]
   workgroup = {}
   server string = Diskless Boot Server
   netbios name = {}
   security = user
   map to guest = Bad User
   dns proxy = no
   
   # Logging
   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file

[{}]
   path = {}
   browseable = yes
   writable = {}
   guest ok = {}
   read only = {}
   create mask = 0755
   directory mask = 0755
   force user = nobody
   force group = nogroup
"#,
            config.workgroup,
            self.settings.server.hostname,
            config.share_name,
            config.share_path.display(),
            if config.read_only { "no" } else { "yes" },
            if config.guest_ok { "yes" } else { "no" },
            if config.read_only { "yes" } else { "no" },
        );

        // Write configuration
        std::fs::write("/etc/samba/smb.conf", smb_conf)?;

        tracing::info!("Samba configuration written to /etc/samba/smb.conf");
        Ok(())
    }
}
