use std::path::PathBuf;

use crate::core::config::Settings;
use crate::services::{get_service_pid, is_systemd_service_running, ServiceStatus};
use tokio::process::Command;

pub struct TftpService {
    settings: Settings,
}

impl TftpService {
    pub fn new(settings: Settings) -> Self {
        Self { settings }
    }

    pub async fn generate_config(&self) -> anyhow::Result<()> {
        let tftp_default = format!(
            r#"TFTP_USERNAME="tftp"
TFTP_DIRECTORY="{}"
TFTP_ADDRESS="0.0.0.0:{}"
TFTP_OPTIONS="--secure --verbose"
"#,
            self.settings.tftp.root_dir.display(),
            self.settings.tftp.port
        );

        // Use pkexec to write to system configuration file
        use tokio::process::Command;
        let mut child = Command::new("pkexec")
            .arg("tee")
            .arg("/etc/default/tftpd-hpa")
            .stdin(std::process::Stdio::piped())
            .stdout(std::process::Stdio::null())
            .spawn()
            .map_err(|e| anyhow::anyhow!("Failed to spawn pkexec tee: {}", e))?;

        if let Some(ref mut stdin) = child.stdin {
            use tokio::io::AsyncWriteExt;
            stdin
                .write_all(tftp_default.as_bytes())
                .await
                .map_err(|e| anyhow::anyhow!("Failed to write config to stdin: {}", e))?;
            stdin
                .flush()
                .await
                .map_err(|e| anyhow::anyhow!("Failed to flush stdin: {}", e))?;
        }

        let status = child
            .wait()
            .await
            .map_err(|e| anyhow::anyhow!("Failed to wait for pkexec tee: {}", e))?;

        if !status.success() {
            return Err(anyhow::anyhow!(
                "Failed to write TFTP config file with pkexec tee"
            ));
        }

        tracing::info!("TFTP configuration written to /etc/default/tftpd-hpa");
        Ok(())
    }

    pub async fn start(&self) -> anyhow::Result<()> {
        // Generate config first
        self.generate_config().await?;

        // Then start tftpd-hpa
        Command::new("pkexec")
            .args(["systemctl", "start", "tftpd-hpa"])
            .status()
            .await?;

        tracing::info!("TFTP service started");
        Ok(())
    }

    pub async fn stop(&self) -> anyhow::Result<()> {
        Command::new("pkexec")
            .args(["systemctl", "stop", "tftpd-hpa"])
            .status()
            .await?;
        tracing::info!("TFTP service stopped");
        Ok(())
    }

    pub async fn reload(&self) -> anyhow::Result<()> {
        Command::new("pkexec")
            .arg("systemctl")
            .args(["restart", "tftpd-hpa"])
            .status()
            .await?;
        tracing::info!("TFTP service reloaded");
        Ok(())
    }

    pub async fn get_config(&self) -> anyhow::Result<String> {
        let config_path = PathBuf::from("/etc/default/tftpd-hpa");
        if config_path.exists() {
            let content = std::fs::read_to_string(&config_path)?;
            Ok(content)
        } else {
            // Return default configuration if file doesn't exist
            let tftp_default = format!(
                r#"# Generated by diskless-boot-server
TFTP_USERNAME="tftp"
TFTP_DIRECTORY="{}"
TFTP_ADDRESS="0.0.0.0:{}"
TFTP_OPTIONS="--secure --verbose"
"#,
                self.settings.tftp.root_dir.display(),
                self.settings.tftp.port
            );
            Ok(tftp_default)
        }
    }

    pub async fn status(&self) -> anyhow::Result<ServiceStatus> {
        let running = is_systemd_service_running("tftpd-hpa").await?;
        let pid = get_service_pid("tftpd-hpa").await?;
        Ok(ServiceStatus {
            running,
            pid,
            message: if running {
                "TFTP server is running".to_string()
            } else {
                "TFTP server is not running".to_string()
            },
        })
    }
}
