use std::path::{Path, PathBuf};
use std::sync::Arc;

use crate::core::config::Settings;
use crate::services::{
    get_service_pid, is_systemd_service_running, run_sudo_command, write_with_sudo_tee,
    ServiceStatus,
};
use log::{info, warn};

pub struct TftpService {
    pub(crate) settings: Arc<Settings>,
}

/// Ensure the TFTP root is labeled so that both `in.tftpd` and Apache can read
/// it. On enforcing SELinux hosts a fresh or reorganized root defaults to
/// `var_t`, which neither daemon may read; `public_content_t` is readable by
/// both server domains.
async fn ensure_root_has_selinux_context(root: &str) {
    let enforce = Path::new("/sys/fs/selinux/enforce");
    if !enforce.exists() {
        return;
    }
    let enforcing = std::fs::read_to_string(enforce)
        .map(|value| value.trim() == "1")
        .unwrap_or(false);
    if !enforcing {
        return;
    }

    let root = Path::new(root);
    if !root.exists() {
        warn!(
            "skipping SELinux labeling of missing TFTP root {}",
            root.display()
        );
        return;
    }

    let spec = format!("{}(/.*)?", root.display());
    if run_sudo_command([
        "semanage",
        "fcontext",
        "-a",
        "-t",
        "public_content_t",
        &spec,
    ])
    .await
    .is_err()
    {
        // A rule already exists; point it at the type we need.
        let _ = run_sudo_command([
            "semanage",
            "fcontext",
            "-m",
            "-t",
            "public_content_t",
            &spec,
        ])
        .await;
    }
    if let Err(error) =
        run_sudo_command(["/usr/sbin/restorecon", "-R", &format!("{}", root.display())]).await
    {
        warn!(
            "failed to relabel TFTP root {} with SELinux type public_content_t: {}",
            root.display(),
            error
        );
    } else {
        info!("labeled {} so TFTP and Apache can read it", root.display());
    }
}

impl TftpService {
    #[expect(
        dead_code,
        reason = "Constructed directly by ServiceManager::new, not by external callers"
    )]
    pub fn new(settings: Settings) -> Self {
        Self {
            settings: Arc::new(settings),
        }
    }

    pub async fn generate_config(&self) -> anyhow::Result<()> {
        let distro = crate::platform::detect();

        // Debian's tftpd-hpa uses named options; Fedora's tftpd uses a single
        // OPTIONS line inside /etc/sysconfig/tftpd; Arch's unit sources
        // /etc/conf.d/tftpd via EnvironmentFile and passes TFTPD_ARGS through
        // to `/usr/bin/in.tftpd --listen`.
        let tftp_default = match distro {
            crate::platform::Distro::Debian => format!(
                r#"TFTP_USERNAME="tftp"
TFTP_DIRECTORY="{}"
TFTP_ADDRESS="{}:{}"
TFTP_OPTIONS="{}"
"#,
                self.settings.tftp.root_dir,
                self.settings.tftp.server_ip,
                self.settings.tftp.port,
                self.settings.tftp.options
            ),
            crate::platform::Distro::RedHat => format!(
                r#"# Generated by diskless-manager
OPTIONS="-s {root} -c -p -U 077 -u tftp -a {ip}:{port}"
"#,
                root = self.settings.tftp.root_dir,
                ip = self.settings.tftp.server_ip,
                port = self.settings.tftp.port,
            ),
            crate::platform::Distro::Arch => format!(
                r#"# Generated by diskless-manager
TFTPD_ARGS="--listen --user tftp --address {ip}:{port} -s {root} {options}"
"#,
                ip = self.settings.tftp.server_ip,
                port = self.settings.tftp.port,
                root = self.settings.tftp.root_dir,
                options = self.settings.tftp.options,
            ),
        };

        let path = distro.tftp_defaults_path();
        write_with_sudo_tee(path, &tftp_default).await?;

        let root_dir = PathBuf::from(&self.settings.tftp.root_dir);
        ensure_root_has_selinux_context(&self.settings.tftp.root_dir).await;

        // The DHCP `filename` hands clients one of these files; flag operator
        // setups where the referenced bootloader is missing from the TFTP root.
        for boot_file in [
            &self.settings.dhcp.boot_file_legacy,
            &self.settings.dhcp.boot_file_uefi32,
            &self.settings.dhcp.boot_file_uefi64,
        ] {
            let path = root_dir.join(boot_file);
            if !path.exists() {
                warn!(
                    "boot file '{}' referenced by the DHCP configuration is missing from {}",
                    boot_file,
                    root_dir.display()
                );
            }
        }

        info!("TFTP configuration written to {}", path);

        // Fedora 44's stock `tftp.service` hard-codes `-s /var/lib/tftpboot`
        // and does not source `/etc/sysconfig/tftpd`. Override ExecStart via a
        // systemd drop-in so the configured root directory is used, regardless
        // of which RedHat variant is running.
        if matches!(distro, crate::platform::Distro::RedHat) {
            let root = &self.settings.tftp.root_dir;
            let options = self.settings.tftp.options.trim();
            let drop_in = format!(
                "# Generated by diskless-manager\n[Service]\nExecStart=\nExecStart=/usr/sbin/in.tftpd -s {root}{extra}\n",
                extra = if options.is_empty() {
                    String::new()
                } else {
                    format!(" {options}")
                }
            );
            let drop_in_path = "/etc/systemd/system/tftp.service.d/diskless-manager.conf";
            let drop_in_dir = "/etc/systemd/system/tftp.service.d";
            run_sudo_command(["mkdir", "-p", drop_in_dir]).await?;
            write_with_sudo_tee(drop_in_path, &drop_in).await?;
            run_sudo_command(["systemctl", "daemon-reload"]).await?;
            info!("TFTP systemd drop-in written to {}", drop_in_path);
        }

        Ok(())
    }

    pub async fn start(&self) -> anyhow::Result<()> {
        // Generate config first
        self.generate_config().await?;

        // Then start the TFTP daemon
        let service = crate::platform::detect().tftp_service();
        run_sudo_command(["systemctl", "start", service]).await?;

        info!("TFTP service started");
        Ok(())
    }

    pub async fn stop(&self) -> anyhow::Result<()> {
        let service = crate::platform::detect().tftp_service();
        run_sudo_command(["systemctl", "stop", service]).await?;
        info!("TFTP service stopped");
        Ok(())
    }

    pub async fn reload(&self) -> anyhow::Result<()> {
        let service = crate::platform::detect().tftp_service();
        run_sudo_command(["systemctl", "restart", service]).await?;
        info!("TFTP service reloaded");
        Ok(())
    }

    pub async fn get_config(&self) -> anyhow::Result<String> {
        let config_path = PathBuf::from(crate::platform::detect().tftp_defaults_path());
        if config_path.exists() {
            let content = std::fs::read_to_string(&config_path)?;
            Ok(content)
        } else {
            // Return default configuration if file doesn't exist
            let tftp_default = format!(
                r#"# Generated by diskless-boot-server
TFTP_USERNAME="tftp"
TFTP_DIRECTORY="{}"
TFTP_ADDRESS="{}:{}"
TFTP_OPTIONS="{}"
"#,
                self.settings.tftp.root_dir,
                self.settings.tftp.server_ip,
                self.settings.tftp.port,
                self.settings.tftp.options
            );
            Ok(tftp_default)
        }
    }

    pub async fn status(&self) -> anyhow::Result<ServiceStatus> {
        let service = crate::platform::detect().tftp_service();
        let running = is_systemd_service_running(service).await?;
        let pid = get_service_pid(service).await?;
        Ok(ServiceStatus {
            running,
            pid,
            message: if running {
                "TFTP server is running".to_string()
            } else {
                "TFTP server is not running".to_string()
            },
        })
    }
}
