#!/usr/bin/env bash
set -euo pipefail

# One-time migration for an existing production server.
# Replaces a legacy hard-coded autoexec.ipxe with the manager-owned generic
# DHCP root-path boot entry. No DHCP or iSCSI state is changed by this script.

ROOT_DIR="${DISKLESS_HTTP_ROOT:-/srv/tftp}"
AUTOEXEC="${ROOT_DIR}/autoexec.ipxe"
BACKUP_DIR="${ROOT_DIR}/backups"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP="${BACKUP_DIR}/autoexec.ipxe.${TIMESTAMP}.bak"

if [[ ! -d "$ROOT_DIR" ]]; then
    echo "ERROR: HTTP/TFTP root does not exist: $ROOT_DIR" >&2
    exit 1
fi

if [[ -e "$AUTOEXEC" ]]; then
    sudo install -d -m 0755 "$BACKUP_DIR"
    sudo cp -a "$AUTOEXEC" "$BACKUP"
    echo "Backed up existing autoexec.ipxe to $BACKUP"
fi

cat <<'IPXE' | sudo tee "$AUTOEXEC" >/dev/null
#!ipxe
# Generated by diskless-manager.
# The client-specific iSCSI root-path is supplied by DHCP.

dhcp
isset ${root-path} || goto no_target

set keep-san 1
echo Booting client SAN target: ${root-path}
sanboot ${root-path} || goto failed

:failed
echo SAN boot failed: ${root-path}
echo Dropping to iPXE shell for diagnostics.
shell

:no_target
echo No iSCSI root-path was supplied by DHCP.
echo This machine is not registered as a diskless client.
shell
IPXE

sudo chmod 0644 "$AUTOEXEC"

if ! grep -Fq 'sanboot ${root-path}' "$AUTOEXEC"; then
    echo "ERROR: generated autoexec.ipxe failed validation" >&2
    exit 1
fi

if grep -Fq 'windows-boot' "$AUTOEXEC" || grep -Fq '4433' "$AUTOEXEC"; then
    echo "ERROR: legacy hard-coded boot configuration remains" >&2
    exit 1
fi

sudo systemctl reload apache2

echo "Installed generic DHCP-root-path autoexec: $AUTOEXEC"
echo "Apache2 reloaded."
echo "This migration does not create or repair iSCSI targets."
