use std::path::Path;

/// Returns a filesystem-safe identifier suitable for a per-client iPXE filename.
#[must_use]
pub fn client_script_slug(client_name: &str) -> String {
    let mut slug = String::with_capacity(client_name.len());
    for byte in client_name.bytes() {
        if byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.') {
            slug.push((byte as char).to_ascii_lowercase());
        } else {
            slug.push('_');
        }
    }

    if slug.is_empty() {
        "client".to_owned()
    } else {
        slug
    }
}

#[must_use]
pub fn client_mac_slug(mac: &str) -> String {
    let slug: String = mac
        .chars()
        .filter(|character| character.is_ascii_hexdigit())
        .map(|character| character.to_ascii_lowercase())
        .collect();

    if slug.len() == 12 {
        slug
    } else {
        "unknown".to_owned()
    }
}

#[must_use]
pub fn client_script_path(client_name: &str) -> String {
    format!("{}.ipxe", client_script_slug(client_name))
}

#[must_use]
pub fn client_mac_script_path(mac: &str) -> String {
    format!("clients/{}.ipxe", client_mac_slug(mac))
}

#[must_use]
pub fn render_client_script(client_name: &str, target_iqn: &str, http_port: u16) -> String {
    render_client_script_with_mode(client_name, target_iqn, http_port, true)
}

#[must_use]
pub fn render_client_script_with_mode(
    client_name: &str,
    target_iqn: &str,
    http_port: u16,
    ready: bool,
) -> String {
    let slug = client_script_slug(client_name);
    let port_suffix = if http_port == 80 {
        String::new()
    } else {
        format!(":{http_port}")
    };

    if !ready {
        return format!(
            r##"#!ipxe
dhcp
# Client is registered but does not have a verified Windows installation.
# Attach its iSCSI disk and boot WinPE for installation.
set client {slug}
set target-iqn {target_iqn}
set boot-url http://${{next-server}}{port_suffix}
set keep-san 1

isset ${{root-path}} || goto no_target
echo Provisioning {slug}: attaching ${{root-path}}
sanhook ${{root-path}} || goto failed

echo Loading Windows PE...
kernel ${{boot-url}}/boot/winpe/wimboot || goto failed
initrd ${{boot-url}}/boot/winpe/bootx64.efi bootx64.efi || goto failed
initrd ${{boot-url}}/boot/winpe/bootmgr bootmgr || goto failed
initrd ${{boot-url}}/boot/winpe/BCD BCD || goto failed
initrd ${{boot-url}}/boot/winpe/boot.sdi boot.sdi || goto failed
initrd ${{boot-url}}/boot/winpe/boot.wim boot.wim || goto failed
boot || goto failed

:no_target
echo No iSCSI root-path was supplied by DHCP.
echo The client cannot be provisioned until a storage target exists.
shell

:failed
echo WinPE provisioning boot failed.
shell
"##,
        );
    }

    let root = format!("/dev/disk/by-path/ip-${{next-server}}:3260-iscsi-{target_iqn}-lun-0-part2");
    let initiator_iqn = format!("iqn.2026-01.client:client.{slug}");

    format!(
        r##"#!ipxe
dhcp
# Client-specific iPXE script generated by diskless-manager.
set client {slug}
set target-iqn {target_iqn}
set initiator-iqn {initiator_iqn}
set boot-url http://${{next-server}}{port_suffix}
set keep-san 1

:start
menu Diskless Boot Menu (Client: ${{client}} - Server IP: ${{next-server}})
item --key b boot_ubuntu    Diskless boot Ubuntu 25.10
item --key a boot_anduinos  Diskless boot Anduin OS 25.04
item --key d boot_debian    Diskless boot Debian 13.2
item --key w boot_windows   Diskless boot Windows 11
item --key i boot_pe       Boot from WinPE (WIM)
item --gap --             ------------------------- Advanced options ------------------------------
item shell               Drop to iPXE shell
item reboot              Reboot computer
choose --timeout 5000 --default boot_windows selected || goto cancel
goto ${{selected}}

:cancel
goto shell

:shell
shell
goto start

:failed
echo Booting failed, dropping to shell
shell

:reboot
reboot

:boot_windows
set keep-san 1
set net0/gateway 0.0.0.0
sanboot ${{root-path}} || goto failed

:boot_pe
set keep-san 1
set net0/gateway 0.0.0.0
sanhook ${{root-path}} || goto failed
kernel ${{boot-url}}/boot/winpe/wimboot || goto failed
initrd ${{boot-url}}/boot/winpe/bootx64.efi bootx64.efi || goto failed
initrd ${{boot-url}}/boot/winpe/bootmgr bootmgr || goto failed
initrd ${{boot-url}}/boot/winpe/BCD BCD || goto failed
initrd ${{boot-url}}/boot/winpe/boot.sdi boot.sdi || goto failed
initrd ${{boot-url}}/boot/winpe/boot.wim boot.wim || goto failed
boot || goto failed

:boot_debian
set net0/gateway 0.0.0.0
sanhook ${{root-path}} || goto failed
kernel ${{boot-url}}/debian/vmlinuz ip=dhcp iscsi_initiator=${{initiator-iqn}} iscsi_target_name=${{target-iqn}} iscsi_target_ip=${{next-server}} root={root} rw rd.iscsi.waitnet=0 rd.iscsi.ibft=1
initrd ${{boot-url}}/debian/initrd.img
boot || goto failed

:boot_ubuntu
set net0/gateway 0.0.0.0
sanhook ${{root-path}} || goto failed
kernel ${{boot-url}}/ubuntu/vmlinuz ip=dhcp iscsi_initiator=${{initiator-iqn}} iscsi_target_name=${{target-iqn}} iscsi_target_ip=${{next-server}} root={root} rw rd.iscsi.waitnet=0 rd.iscsi.ibft=1
initrd ${{boot-url}}/ubuntu/initrd.img
boot || goto failed

:boot_anduinos
set net0/gateway 0.0.0.0
sanhook ${{root-path}} || goto failed
kernel ${{boot-url}}/anduinos/vmlinuz ip=dhcp iscsi_initiator=${{initiator-iqn}} iscsi_target_name=${{target-iqn}} iscsi_target_ip=${{next-server}} root={root} rw rd.iscsi.waitnet=0 rd.iscsi.ibft=1
initrd ${{boot-url}}/anduinos/initrd.img
boot || goto failed
"##,
    )
}

/// Generic PXE entry point. It attaches the DHCP-provided persistent iSCSI
/// disk, attempts Windows SAN boot, and falls back to WinPE on failure.
#[must_use]
pub fn render_autoexec_ipxe(http_port: u16) -> String {
    let port_suffix = if http_port == 80 {
        String::new()
    } else {
        format!(":{http_port}")
    };

    format!(
        r##"#!ipxe
# Generated by diskless-manager.
# Attach the client's persistent iSCSI disk and attempt Windows SAN boot.
# If Windows is not installed/bootable, keep the disk attached and load WinPE.

dhcp
isset ${{root-path}} || goto no_target
set keep-san 1
set net0/gateway 0.0.0.0

echo Attaching client storage: ${{root-path}}
sanhook ${{root-path}} || goto failed
echo Attempting Windows SAN boot...
sanboot --no-describe || goto winpe

:winpe
echo Windows SAN boot is unavailable; entering Windows PE installer.
echo The iSCSI disk remains attached for Windows Setup.
set boot-url http://${{next-server}}{port_suffix}/boot/winpe
kernel ${{boot-url}}/wimboot || goto failed
initrd ${{boot-url}}/bootx64.efi bootx64.efi || goto failed
initrd ${{boot-url}}/bootmgr bootmgr || goto failed
initrd ${{boot-url}}/BCD BCD || goto failed
initrd ${{boot-url}}/boot.sdi boot.sdi || goto failed
initrd ${{boot-url}}/boot.wim boot.wim || goto failed
boot || goto failed

:failed
echo Client boot failed.
echo Verify the iSCSI target and WinPE HTTP files on the server.
shell

:no_target
echo No iSCSI root-path was supplied by DHCP.
echo This machine is not registered as a diskless client.
shell
"##,
    )
}

#[must_use]
pub fn is_managed_script_path(root: &Path, relative_path: &str) -> bool {
    let path = Path::new(relative_path);
    !path.is_absolute()
        && !path
            .components()
            .any(|component| matches!(component, std::path::Component::ParentDir))
        && root.join(path).starts_with(root)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn slug_is_deterministic_and_safe() {
        assert_eq!(client_script_slug("PC 001/West"), "pc_001_west");
        assert_eq!(client_script_path("PC 001/West"), "pc_001_west.ipxe");
    }

    #[test]
    fn mac_slug_is_stable_and_safe() {
        assert_eq!(client_mac_slug("00:11:22:33:44:55"), "001122334455");
        assert_eq!(client_mac_script_path("00:11:22:33:44:55"), "clients/001122334455.ipxe");
        assert_eq!(client_mac_slug("invalid"), "unknown");
    }

    #[test]
    fn script_uses_persisted_target_and_not_hard_coded_pc001() {
        let script = render_client_script("PC002", "iqn.2024-01.com.diskless:client.pc002", 4433);
        assert!(script.contains("set target-iqn iqn.2024-01.com.diskless:client.pc002"));
        assert!(script.contains("iscsi_target_name=${target-iqn}"));
        assert!(script.contains("http://${next-server}:4433"));
        assert!(!script.contains("client.pc001"));
    }

    #[test]
    fn unprovisioned_script_boots_winpe() {
        let script = render_client_script_with_mode("PC001", "iqn.2024-01.com.diskless:client.pc001", 4433, false);
        assert!(script.contains("sanhook ${root-path}"));
        assert!(script.contains("${boot-url}/wimboot"));
        assert!(script.contains("boot.wim boot.wim"));
        assert!(!script.contains("sanboot ${root-path}"));
    }

    #[test]
    fn ready_script_sanboots() {
        let script = render_client_script_with_mode("PC001", "iqn.2024-01.com.diskless:client.pc001", 4433, true);
        assert!(script.contains("sanboot ${root-path}"));
    }

    #[test]
    fn port_80_is_not_rendered_explicitly() {
        let script = render_client_script("PC001", "iqn.example:pc001", 80);
        assert!(script.contains("set boot-url http://${next-server}"));
        assert!(!script.contains("${next-server}:80"));
    }

    #[test]
    fn autoexec_attaches_san_and_falls_back_to_winpe() {
        let script = render_autoexec_ipxe(80);
        assert!(script.starts_with("#!ipxe"));
        assert!(script.contains("sanhook ${root-path}"));
        assert!(script.contains("sanboot --no-describe || goto winpe"));
        assert!(script.contains(":winpe"));
        assert!(script.contains("${boot-url}/wimboot"));
        assert!(script.contains("boot.wim boot.wim"));
        assert!(!script.contains(":4433"));
        assert!(!script.contains("client.pc001"));
    }

    #[test]
    fn autoexec_supports_non_default_http_port() {
        let script = render_autoexec_ipxe(4433);
        assert!(script.contains("http://${next-server}:4433/boot/winpe"));
    }

    #[test]
    fn managed_path_rejects_escape() {
        let root = Path::new("/srv/tftp");
        assert!(is_managed_script_path(root, "pc001.ipxe"));
        assert!(!is_managed_script_path(root, "../pc001.ipxe"));
        assert!(!is_managed_script_path(root, "/etc/passwd"));
    }
}
