use std::path::Path;

/// Returns a filesystem-safe identifier suitable for a per-client iPXE filename.
#[must_use]
pub fn client_script_slug(client_name: &str) -> String {
    let mut slug = String::with_capacity(client_name.len());
    for byte in client_name.bytes() {
        if byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.') {
            slug.push((byte as char).to_ascii_lowercase());
        } else {
            slug.push('_');
        }
    }

    if slug.is_empty() {
        "client".to_owned()
    } else {
        slug
    }
}

/// Returns a stable filesystem/URL-safe identifier for a client MAC address.
#[must_use]
pub fn client_mac_slug(mac: &str) -> String {
    let slug: String = mac
        .chars()
        .filter(|character| character.is_ascii_hexdigit())
        .map(|character| character.to_ascii_lowercase())
        .collect();

    if slug.len() == 12 {
        slug
    } else {
        "unknown".to_owned()
    }
}

/// Returns the relative HTTP/TFTP path for a client-specific boot script.
#[must_use]
pub fn client_script_path(client_name: &str) -> String {
    format!("{}.ipxe", client_script_slug(client_name))
}

/// Returns the relative HTTP path for a MAC-address-specific boot dispatcher.
#[must_use]
pub fn client_mac_script_path(mac: &str) -> String {
    format!("clients/{}.ipxe", client_mac_slug(mac))
}

/// Builds a client-specific iPXE script from the persisted target IQN.
#[must_use]
pub fn render_client_script(client_name: &str, target_iqn: &str, http_port: u16) -> String {
    render_client_script_with_mode(client_name, target_iqn, http_port, true)
}

/// Builds the boot script for a client. Unprovisioned clients enter WinPE so
/// Windows can be installed onto their iSCSI disk; ready clients SAN-boot the
/// installed Windows volume.
#[must_use]
pub fn render_client_script_with_mode(
    client_name: &str,
    target_iqn: &str,
    http_port: u16,
    ready: bool,
) -> String {
    let slug = client_script_slug(client_name);
    let port_suffix = if http_port == 80 {
        String::new()
    } else {
        format!(":{http_port}")
    };

    if !ready {
        return format!(
            r##"#!ipxe
dhcp
# Client is registered but does not have a verified Windows installation.
# Attach its iSCSI disk and boot WinPE for installation.
set client {slug}
set target-iqn {target_iqn}
set boot-url http://${{next-server}}{port_suffix}
set keep-san 1

isset ${{root-path}} || goto no_target
echo Provisioning {slug}: attaching ${{root-path}}
sanhook ${{root-path}} || goto failed

echo Loading Windows PE...
kernel ${{boot-url}}/boot/winpe/wimboot || goto failed
initrd ${{boot-url}}/boot/winpe/bootx64.efi bootx64.efi || goto failed
initrd ${{boot-url}}/boot/winpe/bootmgr bootmgr || goto failed
initrd ${{boot-url}}/boot/winpe/BCD BCD || goto failed
initrd ${{boot-url}}/boot/winpe/boot.sdi boot.sdi || goto failed
initrd ${{boot-url}}/boot/winpe/boot.wim boot.wim || goto failed
boot || goto failed

:no_target
echo No iSCSI root-path was supplied by DHCP.
echo The client cannot be provisioned until a storage target exists.
shell

:failed
echo WinPE provisioning boot failed.
shell
"##,
        );
    }

    let root = format!("/dev/disk/by-path/ip-${{next-server}}:3260-iscsi-{target_iqn}-lun-0-part2");
    let initiator_iqn = format!("iqn.2026-01.client:client.{slug}");

    format!(
        r##"#!ipxe
dhcp
# Client-specific diskless boot script generated by diskless-manager.
set client {slug}
set target-iqn {target_iqn}
set initiator-iqn {initiator_iqn}
set boot-url http://${{next-server}}{port_suffix}
set keep-san 1

:start
menu Diskless Boot Menu (Client: ${{client}} - Server IP: ${{next-server}})
item --gap --             ------------------------- Operating systems ------------------------------
item --key b boot_ubuntu    Diskless boot Ubuntu 25.10
item --key a boot_anduinos  Diskless boot Anduin OS 25.04
item --key d boot_debian    Diskless boot Debian 13.2
item --key w boot_windows   Diskless boot Windows 11
item --key i boot_pe       Boot from WinPE (WIM)
item --key i boot_pe_iso   Boot from WinPE (ISO)
item --gap --             ------------------------- Advanced options -------------------------------
item --key c config       Configure settings
item shell               Drop to iPXE shell
item reboot              Reboot computer
item
item --key x exit         Exit iPXE and continue BIOS boot
choose --timeout 5000 --default boot_windows selected || goto cancel
set menu-timeout 0
goto ${{selected}}

:cancel
echo You cancelled the menu, dropping you to a shell
goto shell

:shell
echo Type 'exit' to get back to the menu
shell
goto start

:failed
echo Booting failed, dropping to shell
goto shell

:reboot
reboot

:exit
exit

:config
config
goto start

:boot_windows
set keep-san 1
set net0/gateway 0.0.0.0
sanboot ${{root-path}} || goto failed

:boot_pe_iso
echo ${{root-path}}
set keep-san 1
set net0/gateway 0.0.0.0
sanhook ${{root-path}} || goto failed
sanboot --drive 0x81 ${{boot-url}}/winpe.iso || goto failed

:boot_pe
echo ${{root-path}}
set keep-san 1
set net0/gateway 0.0.0.0
sanhook ${{root-path}} || goto failed
kernel ${{boot-url}}/boot/winpe/wimboot
initrd ${{boot-url}}/boot/winpe/bootx64.efi bootx64.efi || goto failed
initrd ${{boot-url}}/boot/winpe/bootmgr bootmgr || goto failed
initrd ${{boot-url}}/boot/winpe/BCD BCD || goto failed
initrd ${{boot-url}}/boot/winpe/boot.sdi boot.sdi || goto failed
initrd ${{boot-url}}/boot/winpe/boot.wim boot.wim || goto failed
boot || goto failed

:boot_debian
set net0/gateway 0.0.0.0
sanhook ${{root-path}} || goto failed
kernel ${{boot-url}}/debian/vmlinuz \
    ip=dhcp \
    iscsi_initiator=${{initiator-iqn}} \
    iscsi_target_name=${{target-iqn}} \
    iscsi_target_ip=${{next-server}} \
    root={root} \
    rw \
    rd.iscsi.waitnet=0 \
    rd.iscsi.ibft=1 \
    rd.net.ifnames=0 \
    rd.iscsi.param=node.conn[0].iscsi.MaxRecvDataSegmentLength:262144 \
    rd.iscsi.param=node.conn[0].iscsi.MaxXmitDataSegmentLength:262144 \
    rd.iscsi.param=node.conn[0].iscsi.FirstBurstLength:262144 \
    rd.iscsi.param=node.conn[0].iscsi.MaxBurstLength:4194304
initrd ${{boot-url}}/debian/initrd.img
boot || goto failed

:boot_ubuntu
set net0/gateway 0.0.0.0
sanhook ${{root-path}} || goto failed
kernel ${{boot-url}}/ubuntu/vmlinuz \
    ip=dhcp \
    iscsi_initiator=${{initiator-iqn}} \
    iscsi_target_name=${{target-iqn}} \
    iscsi_target_ip=${{next-server}} \
    root={root} \
    rw \
    rd.iscsi.waitnet=0 \
    rd.iscsi.ibft=1 \
    rd.net.ifnames=0 \
    rd.iscsi.param=node.conn[0].iscsi.MaxRecvDataSegmentLength:262144 \
    rd.iscsi.param=node.conn[0].iscsi.MaxXmitDataSegmentLength:262144 \
    rd.iscsi.param=node.conn[0].iscsi.FirstBurstLength:262144 \
    rd.iscsi.param=node.conn[0].iscsi.MaxBurstLength:4194304
initrd ${{boot-url}}/ubuntu/initrd.img
boot || goto failed

:boot_anduinos
set net0/gateway 0.0.0.0
sanhook ${{root-path}} || goto failed
kernel ${{boot-url}}/anduinos/vmlinuz \
    ip=dhcp \
    iscsi_initiator=${{initiator-iqn}} \
    iscsi_target_name=${{target-iqn}} \
    iscsi_target_ip=${{next-server}} \
    root={root} \
    rw \
    rd.iscsi.waitnet=0 \
    rd.iscsi.ibft=1 \
    rd.net.ifnames=0 \
    rd.iscsi.param=node.conn[0].iscsi.MaxRecvDataSegmentLength:262144 \
    rd.iscsi.param=node.conn[0].iscsi.MaxXmitDataSegmentLength:262144 \
    rd.iscsi.param=node.conn[0].iscsi.FirstBurstLength:262144 \
    rd.iscsi.param=node.conn[0].iscsi.MaxBurstLength:4194304
initrd ${{boot-url}}/anduinos/initrd.img
boot || goto failed
"##,
    )
}

/// Generic PXE entry point used after DHCP has chainloaded iPXE.
///
/// The per-client dispatcher is selected from the DHCP MAC address. This
/// keeps boot state out of the global script and allows an unprovisioned client
/// to enter WinPE while ready clients SAN-boot normally.
#[must_use]
pub fn render_autoexec_ipxe() -> &'static str {
    r#"#!ipxe
# Generated by diskless-manager.
# Dispatch to the stateful boot script generated for this client's MAC.

dhcp
isset ${net0/mac} || goto no_mac
set client-mac ${net0/mac:hexraw}
echo Loading boot policy for ${client-mac}
chain http://${next-server}/clients/${client-mac}.ipxe || goto failed

:failed
echo Client boot policy could not be loaded.
echo This machine may not be registered or its boot policy is unavailable.
shell

:no_mac
echo No network adapter MAC address is available.
shell
"#
}

/// Validates that a generated client script path remains beneath the managed root.
#[must_use]
pub fn is_managed_script_path(root: &Path, relative_path: &str) -> bool {
    let path = Path::new(relative_path);
    !path.is_absolute()
        && !path
            .components()
            .any(|component| matches!(component, std::path::Component::ParentDir))
        && root.join(path).starts_with(root)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn slug_is_deterministic_and_safe() {
        assert_eq!(client_script_slug("PC 001/West"), "pc_001_west");
        assert_eq!(client_script_path("PC 001/West"), "pc_001_west.ipxe");
    }

    #[test]
    fn mac_slug_is_stable_and_safe() {
        assert_eq!(client_mac_slug("00:11:22:33:44:55"), "001122334455");
        assert_eq!(client_mac_script_path("00:11:22:33:44:55"), "clients/001122334455.ipxe");
        assert_eq!(client_mac_slug("invalid"), "unknown");
    }

    #[test]
    fn script_uses_persisted_target_and_not_hard_coded_pc001() {
        let script = render_client_script("PC002", "iqn.2024-01.com.diskless:client.pc002", 4433);
        assert!(script.contains("set target-iqn iqn.2024-01.com.diskless:client.pc002"));
        assert!(script.contains("iscsi_target_name=${target-iqn}"));
        assert!(script.contains("http://${next-server}:4433"));
        assert!(!script.contains("client.pc001"));
    }

    #[test]
    fn unprovisioned_script_boots_winpe() {
        let script = render_client_script_with_mode(
            "PC001",
            "iqn.2024-01.com.diskless:client.pc001",
            4433,
            false,
        );
        assert!(script.contains("sanhook ${root-path}"));
        assert!(script.contains("/boot/winpe/wimboot"));
        assert!(script.contains("boot.wim boot.wim"));
        assert!(!script.contains("sanboot ${root-path}"));
    }

    #[test]
    fn ready_script_sanboots() {
        let script = render_client_script_with_mode(
            "PC001",
            "iqn.2024-01.com.diskless:client.pc001",
            4433,
            true,
        );
        assert!(script.contains("sanboot ${root-path}"));
    }

    #[test]
    fn port_80_is_not_rendered_explicitly() {
        let script = render_client_script("PC001", "iqn.example:pc001", 80);
        assert!(script.contains("set boot-url http://${next-server}"));
        assert!(!script.contains("${next-server}:80"));
    }

    #[test]
    fn autoexec_is_generic_and_dispatches_by_mac() {
        let script = render_autoexec_ipxe();
        assert!(script.starts_with("#!ipxe"));
        assert!(script.contains("dhcp"));
        assert!(script.contains("${net0/mac:hexraw}"));
        assert!(script.contains("/clients/${client-mac}.ipxe"));
        assert!(!script.contains("windows-boot"));
        assert!(!script.contains("client.pc001"));
    }

    #[test]
    fn managed_path_rejects_escape() {
        let root = Path::new("/srv/tftp");
        assert!(is_managed_script_path(root, "pc001.ipxe"));
        assert!(!is_managed_script_path(root, "../pc001.ipxe"));
        assert!(!is_managed_script_path(root, "/etc/passwd"));
    }
}
