name: "Publish Release"
on:
  push:
    tags:
      - "v*"
    branches: "*"
  workflow_dispatch:

env:
  APP_NAME: "Diskless Boot Server"

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build changelog
        id: build_changelog
        run: |
          TAGS=$(git tag --list 'v*' --sort=-version:refname)
          TAG_COUNT=$(echo "$TAGS" | wc -l)
          if [ $TAG_COUNT -le 1 ]; then
            changelog=$(git log --pretty=format:"- %s")
          else
            PREV_TAG=$(echo "$TAGS" | tail -n +2 | head -n1)
            changelog=$(git log $PREV_TAG..${{ github.ref_name }} --pretty=format:"- %s")
          fi
          echo "changelog=$changelog" >> $GITHUB_OUTPUT
    outputs:
      changelog: ${{ steps.build_changelog.outputs.changelog }}
  release:
    needs: changelog
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "ubuntu-latest"
            args: ""
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Install frontend dependencies
        run: bun install

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        # if u get Error: Resource not accessible by integration
        # go to repository Settings => Action => General => Workflow permissions => Switch to Read and Write permisions
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          # tauri-action replaces \_\_VERSION\_\_ with the app version
          tagName: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
          releaseName: ${{ github.ref_type == 'tag' && format('%s v__VERSION__', env.APP_NAME) || '' }}
          releaseBody: ${{ github.ref_type == 'tag' && format('%s\n\nSee the assets to download this version and install.', needs.changelog.outputs.changelog) || '' }}
          releaseDraft: ${{ github.ref_type == 'tag' }}
          prerelease: false
          args: ${{ matrix.args }}

      - name: CI upload Linux
        if: ${{ github.ref_type == 'branch' && matrix.platform == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: "Linux Distributions"
          path: |
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/AppImage/*.AppImage
